version: '3.8'

services:
    django:
        build: .
        container_name: django
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
            - CELERY_BROKER=redis://redis:6379/0
        depends_on:
            - redis

    celery:
        build: .
        command: celery -A sterling_square worker -l info
        volumes:
            - .:/usr/src/app
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        depends_on:
            - django
            - redis
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]

    celery_beat:
        build: .
        command: celery -A sterling_square beat -l info
        volumes:
            - .:/usr/src/app
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        depends_on:
            - django
            - redis
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]

    selenium:
        image: selenium/standalone-chrome
        ports:
        - 4444:4444

    redis:
        image: "redis:alpine"
        command: redis-server
        healthcheck:
            test: redis-cli ping
            interval: 3s
            timeout: 5s
            retries: 5

    redisinsight:
        image: 'redislabs/redisinsight:latest'
        ports:
            - '127.0.0.1:8001:8001'